# 23. Python Advanced Programming Assignment

1. Create a class Sudoku that takes a string as an argument. The string will contain the numbers of a regular 9x9 sudoku board left to right and top to bottom, with zeros filling up the empty cells.

Attributes

An instance of the class Sudoku will have one attribute:

   - board: a list representing the board, with sublits for each row, with the numbers as integers. Empty cell represented with 0.

Methods

An instance of the class Sudoku wil have three methods:

   - get_row(n): will return the row in position n.
   - get_col(n): will return the column in position n.
   - get_sqr([n, m]): will return the square in position n if only one argument is given, and the square to which the cell in position (n, m) belongs to if two arguments are given.

Example


















game = Sudoku("417950030000000700060007000050009106800600000000003400900005000000430000200701580")


game.board ➞ [
  [4, 1, 7, 9, 5, 0, 0, 3, 0],
  [0, 0, 0, 0, 0, 0, 7, 0, 0],
  [0, 6, 0, 0, 0, 7, 0, 0, 0],
  [0, 5, 0, 0, 0, 9, 1, 0, 6],
  [8, 0, 0, 6, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 3, 4, 0, 0],
  [9, 0, 0, 0, 0, 5, 0, 0, 0],
  [0, 0, 0, 4, 3, 0, 0, 0, 0],
  [2, 0, 0, 7, 0, 1, 5, 8, 0]
]

game.get_row(0) ➞ [4, 1, 7, 9, 5, 0, 0, 3, 0]
game.get_col(8) ➞ [0, 0, 0, 6, 0, 0, 0, 0, 0]
game.get_sqr(1) ➞ [9, 5, 0, 0, 0, 0, 0, 0, 7]
game.get_sqr(1, 8) ➞ [0, 3, 0, 7, 0, 0, 0, 0, 0]
game.get_sqr(8, 3) ➞ [0, 0, 5, 4, 3, 0, 7, 0, 1]

In [54]:
import numpy as np
class Sudoku:
    def __init__(self, num_str):
        self.num_str=num_str
        
        list_=[]
        for num in self.num_str:
            list_.append(int(num))
        
        self.gameboard = np.array(list_).reshape(9,9)
        
    def get_row(self,n):
        return self.gameboard[n]
    
    def get_col(self,n):
        return self.gameboard[:,n]
    
    def get_sqr(self,n,m=0):
        square_dict={
        0:self.gameboard[:3,:3],
        1:self.gameboard[:3,3:6],
        2:self.gameboard[:3,6:9],
        3:self.gameboard[3:6,:3],
        4:self.gameboard[3:6,3:6],
        5:self.gameboard[3:6,6:9],
        6:self.gameboard[6:9,:3],
        7:self.gameboard[6:9,3:6],
        8:self.gameboard[6:9,6:9]
        }
        if m==0:
            return square_dict[n]
        else:
            if n>=0 and n<=2 and m >=0 and m<=2:
                return square_dict[0]
            elif n>=0 and n<=2 and m >=3 and m<=5:
                return square_dict[1]
            elif n>=0 and n<=2 and m >=6 and m<=8:
                return square_dict[2]
            if n>=3 and n<=5 and m >=0 and m<=2:
                return square_dict[3]
            elif n>=3 and n<=5 and m >=3 and m<=5:
                return square_dict[4]
            elif n>=3 and n<=5 and m >=6 and m<=8:
                return square_dict[5]
            if n>=6 and n<=8 and m >=0 and m<=2:
                return square_dict[0]
            elif n>=6 and n<=8 and m >=3 and m<=5:
                return square_dict[1]
            elif n>=6 and n<=8 and m >=6 and m<=8:
                return square_dict[1]
        
game = Sudoku("417950030000000700060007000050009106800600000000003400900005000000430000200701580")
print(game.gameboard)            
print(game.get_row(0)) 
print(game.get_col(8))
print(game.get_sqr(1))
print(game.get_sqr(1,8))

[[4 1 7 9 5 0 0 3 0]
 [0 0 0 0 0 0 7 0 0]
 [0 6 0 0 0 7 0 0 0]
 [0 5 0 0 0 9 1 0 6]
 [8 0 0 6 0 0 0 0 0]
 [0 0 0 0 0 3 4 0 0]
 [9 0 0 0 0 5 0 0 0]
 [0 0 0 4 3 0 0 0 0]
 [2 0 0 7 0 1 5 8 0]]
[4 1 7 9 5 0 0 3 0]
[0 0 0 6 0 0 0 0 0]
[[9 5 0]
 [0 0 0]
 [0 0 7]]
[[0 3 0]
 [7 0 0]
 [0 0 0]]


2. The function input is two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list, in which the digits are also stored in reversed order. The class ListNode, building block of the linked list, is defined in the Tests tab.

Class definition

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

Examples

lt1 = ListNode(2)
lt1.add_data([4, 3])
lt2 = ListNode(5)
lt2.add_data([6, 4])
print(lt1.get_data())    # [2, 4, 3]
print(lt2.get_data())    # [5, 6, 4]
print(342 + 465)         # 807
add_two_numbers(lt1, lt2).get_data() ➞ [7, 0, 8]

lt1 = ListNode(0)
lt2 = ListNode(0)
print(lt1.get_data())    # [0]
print(lt2.get_data())    # [0]
print(0 + 0)             # 0
add_two_numbers(lt1, lt2).get_data() ➞ [0]

lt1 = ListNode(9)
lt1.add_data([9,9,9,9,9,9])
lt2 = ListNode(9)
lt2.add_data([9,9,9])
print(lt1.get_data())    # [9, 9, 9, 9, 9, 9, 9]
print(lt2.get_data())    # [9, 9, 9, 9]
print(9999999 + 9999)    # 10009998
add_two_numbers(lt1, lt2).get_data() ➞ [8, 9, 9, 9, 0, 0, 0, 1]


In [71]:
class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next
        
    def add_data(self, num_list):
        self.num_list=num_list
        self.num_list.append(self.val)
        
    def get_data(self):
        return self.num_list[::-1]
    
class add_two_numbers:
    def __init__(self,list1,list2):
        self.list1=list1
        self.list2=list2
        
        
    def get_data(self):
        for i in self.list1:
            print(i)
            
lt1 = ListNode(2)
lt1.add_data([4, 3])
lt2 = ListNode(5)
lt2.add_data([6, 4])
print(lt1.get_data())    
print(lt2.get_data())


[2, 3, 4]
[5, 4, 6]


3. Write a class called CoffeeShop, which has three instance variables:

   1. name : a string (basically, of the shop)
   2. menu : a list of items (of dict type), with each item containing the item (name of the item), type (whether a food or a drink) and price.
   3. orders : an empty list

and seven methods:

  1. add_order: adds the name of the item to the end of the orders list if it exists on the menu, otherwise, return "This item is currently unavailable!"
  2. fulfill_order: if the orders list is not empty, return "The {item} is ready!". If the orders list is empty, return "All orders have been fulfilled!"
  3. list_orders: returns the item names of the orders taken, otherwise, an empty list.
  4. due_amount: returns the total amount due for the orders taken.
  5. cheapest_item: returns the name of the cheapest item on the menu.
  6. drinks_only: returns only the item names of type drink from the menu.
  7. food_only: returns only the item names of type food from the menu.

IMPORTANT: Orders are fulfilled in a FIFO (first-in, first-out) order.

Examples

tcs.add_order("hot cocoa") ➞ "This item is currently unavailable!"
# Tesha's coffee shop does not sell hot cocoa
tcs.add_order("iced tea") ➞ "This item is currently unavailable!"
# specifying the variant of "iced tea" will help the process

tcs.add_order("cinnamon roll") ➞  "Order added!"
tcs.add_order("iced coffee") ➞ "Order added!"
tcs.list_orders ➞ ["cinnamon roll", "iced coffee"]
# all items of the current order

tcs.due_amount() ➞ 2.17

tcs.fulfill_order() ➞ "The cinnamon roll is ready!"
tcs.fulfill_order() ➞ "The iced coffee is ready!"
tcs.fulfill_order() ➞ "All orders have been fulfilled!"
# all orders have been presumably served

tcs.list_orders() ➞ []
# an empty list is returned if all orders have been exhausted

tcs.due_amount() ➞ 0.0
# no new orders taken, expect a zero payable

tcs.cheapest_item() ➞ "lemonade"
tcs.drinks_only() ➞ ["orange juice", "lemonade", "cranberry juice", "pineapple juice", "lemon iced tea", "vanilla chai latte", "hot chocolate", "iced coffee"]
tcs.food_only() ➞ ["tuna sandwich", "ham and cheese sandwich", "bacon and egg", "steak", "hamburger", "cinnamon roll"]



In [49]:
menu={"orange juice":["drink",3], "lemonade":["drink",1], "cranberry juice":["drink",4], "pineapple juice":["drink",2],
      "lemon iced tea":["drink",3],"vanilla chai latte":["drink",4], "hot chocolate":["drink",2], "iced coffee":["drink",3],
     "tuna sandwich":["food",5], "ham and cheese sandwich":["food",6], "bacon and egg":["food",7], "steak":["food",5], 
      "hamburger":["food",6], "cinnamon roll":["food",7]}
orders=[]

class CoffeeShop:
    def __init__(self, name, menu, orders):
        self.name=name
        self.menu=menu
        self.orders=orders
    
    def add_order(self, order):
        if order in self.menu.keys():
            self.orders.append(order)
            print("Order added!")
        else:
            print("This item is currently unavailable!")
            
    def fulfill_order(self):
        if len(self.orders) != 0:
            print("The", self.orders[0] , "is ready")
            del self.orders[0]
        else:
            print("All orders have been fulfilled!")
            
    def list_orders(self):
        return self.orders
    
    def due_amount(self):
        amount=0
        for order in self.orders:
            amount+=menu[order][1]
        
        return amount
    
    def cheapest_item(self):
        cheapest=["lemonade"]
        cheap=menu["lemonade"][1]
        for order in self.menu:
            if menu[order][1] < cheap:
                cheapest.append(order)
        return cheapest
    
    def drinks_only(self):
        drinks=[]
        
        for item in self.menu.keys():
            if self.menu[item][0] == "drink":
                drinks.append(item)
    
        return drinks
            
    def food_only(self):
        food=[]
        
        for item in self.menu.keys():
            if self.menu[item][0] == "food":
                food.append(item)
    
        return food
               
tcs=CoffeeShop("tcs",menu,orders)
tcs.add_order("hot cocoa") 
tcs.add_order("iced tea") 
tcs.add_order("cinnamon roll") 
tcs.add_order("iced coffee") 
print(tcs.list_orders() )
print(tcs.due_amount() )
tcs.fulfill_order() 
tcs.fulfill_order() 
tcs.fulfill_order() 
print(tcs.list_orders())
print(tcs.due_amount() )
print(tcs.cheapest_item())
print(tcs.drinks_only() )
print(tcs.food_only())

This item is currently unavailable!
This item is currently unavailable!
Order added!
Order added!
['cinnamon roll', 'iced coffee']
10
The cinnamon roll is ready
The iced coffee is ready
All orders have been fulfilled!
[]
0
['lemonade']
['orange juice', 'lemonade', 'cranberry juice', 'pineapple juice', 'lemon iced tea', 'vanilla chai latte', 'hot chocolate', 'iced coffee']
['tuna sandwich', 'ham and cheese sandwich', 'bacon and egg', 'steak', 'hamburger', 'cinnamon roll']


In [13]:
class loneliest_number :
    def __init__(self, lo, hi):
        self.lo=lo
        self.hi=hi
        
        self.number=0
        self.distance=0
        self.closest=0
        
        self.prime_list=[]
        
        for i in range(self.lo, self.hi+1):
            if i>1:
                for j in range(2,i):
                    if(i % j==0):
                        break
                else:
                    self.prime_list.append(i)
                    
    def check(self):
        self.number=self.prime_list[0]
        
        for i in range(1,len(self.prime_list)-1):
            if (self.prime_list[i+1] - self.prime_list[i] > self.distance) or (self.prime_list[i-1]  - self.prime_list[i] > self.distance):
                self.number=self.prime_list[i]
                self.distance=max (self.prime_list[i+1] - self.prime_list[i],self.prime_list[i-1]  - self.prime_list[i])
                self.closest= self.prime_list[i+1]
            
        return { "number" : self.number , 'distance': self.distance,'closest' : self.closest }


                
l=loneliest_number(8,123)
print(l.check())

{'number': 89, 'distance': 8, 'closest': 97}


In [24]:
class Selfie:
    def __init__(self,x):
        self.x=x
        self.state=[]
        
    def return_state(self):
        return self.x
    
    def save_state(self):
        self.state.append(self.x)
        print(self.state)
     
    def recover_state(self,y):
        if y >= 0 and y < len(self.state):
            self.x=self.state[y]
            return self.state[y]
        else:
            return self.x
    
    
    
p = Selfie(0)
p.x = 2
print(p.return_state())
p.save_state()
p.x = 5
p.save_state()
print(p.return_state())
p.recover_state(0)
print(p.return_state())

2
[2]
[2, 5]
5
2
